name: flutter_template_flavor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Router
  go_router: ^6.0.1
  # State managemant
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  # Network
  dio: ^4.0.6
  retrofit: ^3.3.1
  # DI
  get_it: ^7.2.0
  injectable: ^2.1.0
  # Gen
  freezed_annotation: ^2.2.0
  # Storage/Cache
  hive: ^2.2.3
  cached_network_image: ^3.2.3
  # Other
  logging: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Gen
  build_runner: ^2.3.3
  retrofit_generator: ^4.2.0
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  injectable_generator: ^2.1.3
  flutter_gen_runner: ^5.1.0+1

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    # flutter_svg: true
    # flare_flutter: true
    # rive: true
    # lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/Sarabun-Italic.ttf
          style: italic
